name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18.10'

      - name: Install dependencies
        run: |
          npm i
          npm run build

      - name: Package app
        run: |
          npx electron-builder --${{ matrix.os }} --publish always

      - name: Publish to GitHub Package Registry
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.os }}-package
          path: dist

      - name: Release app
        if: startsWith(github.ref, 'refs/tags/v')
        uses: samuelmeuli/release-drafter@v7
        with:
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref }}
          name-template: '{{ tag }}'
          body-template: |
            {{#each commits}}
            - {{subject}}
            {{/each}}

          draft: false
          prerelease: false

    env:
      NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
