name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build and Package for Linux, macOS, and Windows
        run: |
          npm run build
          npx electron-builder --linux snap --armv7l --publish always
          npx electron-builder --linux snap --x64 --publish always
          npx electron-builder --linux deb rpm --x64 --publish always
          npx electron-builder --linux deb --arm64 --publish always
          npx electron-builder --linux deb --armv7l --publish always
          npx electron-builder --linux AppImage --x64 --publish always
          npx electron-builder --linux AppImage --arm64 --publish always
          npx electron-builder --linux AppImage --armv7l --publish always
          npx electron-builder --macos --publish always
          npx electron-builder --windows nsis:7z:squirrel --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Release Electron app - MacOS
        if: startsWith(matrix.os, 'macos')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Release Electron app - Windows
        if: startsWith(matrix.os, 'windows')
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
