name: Release
on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  package:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Package Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: |
          npm ci
          npm run build
          npx electron-builder --linux snap --armv7l --publish always
          npx electron-builder --linux snap --x64 --publish always
          npx electron-builder --linux deb rpm --x64 --publish always
          npx electron-builder --linux deb --arm64 --publish always
          npx electron-builder --linux deb --armv7l --publish always
          npx electron-builder --linux AppImage --x64 --publish always
          npx electron-builder --linux AppImage --arm64 --publish always
          npx electron-builder --linux AppImage --armv7l --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release Electron app - MacOS
        if: matrix.os == 'macos-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Release Electron app - Windows
        if: matrix.os == 'windows-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
